### ISSUE TITLE
Offline devices cleanup 

### ISSUE THREAD

**Issue by aAbdman** [uvjim/linksys_velop#201]
Hello Uvjim,

Is there a way to delete all offline device.
I tried creating a script but with no luck.

```
alias: Linksys Delete Offline Devices
sequence:
  - service: linksys_velop.delete_device
    data:
      mesh: 57575757657657657657657575
      device_name: >-
        {% set Devices = state_attr ('sensor.velop_mesh_offline_devices',
        'devices') %}  {% for Devices in Devices %}  {{ Devices }}  {% endfor %}
mode: single
```

any advice?

**Comment by uvjim** [comment]
I've tested this quickly as a script to create persistent notifications and it works. I guess you could adapt this to do the delete for you.

```
alias: Remove Offline Devices
sequence:
  - repeat:
      for_each: '{{ state_attr(''sensor.velop_mesh_offline_devices'', ''devices'') }}'
      sequence:
        - service: persistent_notification.create
          data:
            title: Test
            message: '{{ repeat.item }}'
mode: single
```

**Comment by aAbdman** [comment]
Thanks for the code
I tried the following script

```
alias: Linksys Remove IoT Offline Devices
sequence:
  - repeat:
      for_each: '{{ state_attr(''sensor.velop_iot_offline_devices'', ''devices'') }}'
      sequence:
        - service: linksys_velop.delete_device
          data:
            mesh: 0000000000000000000000000
            device_name: '{{ repeat.item }}'
        - service: persistent_notification.create
          data:
            message: '{{ repeat.item }}'
mode: single
```

it goes through the process successfully but only a couple of device seems to be removed.
I have to mention that I am using Linksys as a bridge mode connected to a pfsense router.

Any way, I will keep trying and appreciate any insight otherwise feel free to close the post as done.

Thanks & Cheers

**Comment by uvjim** [comment]
Is there anything in the logs? I know when deleting by name, if there is more than one device with the same name an error should be raised because it won't know which to delete.

**Comment by aAbdman** [comment]
You are right!

```
This error originated from a custom integration.

Logger: custom_components.linksys_velop.service_handler
Source: custom_components/linksys_velop/service_handler.py:122
Integration: Linksys Velop (documentation, issues)
First occurred: 15:34:37 (52 occurrences)
Last logged: 15:34:40

_async_service_call (32N10M32B01257) --> Too Many Matches
```

Would deleting by ID work?

**Comment by uvjim** [comment]
Yes, because the ID is unique. IIRC the ID is not available in the offline sensor though.

There's no real reason why it couldn't be. I'd just need to adjust the sensor definition. Then in your loop you'd pull out the ID rather than the name.

**Comment by aAbdman** [comment]
That would be great 

Thanks Uvjim 🙏🏼

**Comment by uvjim** [comment]
Leave it with me. It'll cause a breaking change for people that rely on the attribute just being a list but it should be easy enough for them to switch to an object.

**Comment by aAbdman** [comment]
sure 👍🏼

**Comment by uvjim** [comment]
`2022.5.3b0` has now been released which should add the required info for you.

I've extended the original notofication script from earlier to reflect using the new object.  Feel free to tweak again.

```
alias: Remove Offline Devices
sequence:
  - repeat:
      for_each: '{{ state_attr(''sensor.velop_mesh_offline_devices'', ''devices'') }}'
      sequence:
        - service: persistent_notification.create
          data:
            title: '{{ repeat.item.name }}'
            message: 'Unique ID: {{ repeat.item.id }}'
mode: single
```
