### ISSUE TITLE
Mesh Card / Node Card - Reboot Options

### ISSUE THREAD

**Issue by mschingel** [uvjim/linksys_velop#322]
Looking for an enhancement or fix to the Reboot function of the cards

![image](https://user-images.githubusercontent.com/109315303/202236859-bcb6ffbc-c5da-4d9b-bdfb-45bf65449429.png)

I receive this error when pressing the reboot button on the Garage Node
![image](https://user-images.githubusercontent.com/109315303/202237216-9991cfb9-b3e1-4279-ae9e-9decf492e5c1.png)

Picture of the Nodes and Mesh
![image](https://user-images.githubusercontent.com/109315303/202237940-2b978012-755f-44aa-8b8d-08fc9edd63e4.png)

I think the error comes in play BC the mesh isn't defined in card. But reviewing the code I didn't see where mesh: data was located.

Calling this service Does work to reset the Nodes.
![image](https://user-images.githubusercontent.com/109315303/202238197-ac28b66b-aeaa-4e06-9c6e-1f22caed3d06.png)

Request:

Can you move or add the "actions" from the Node cards to the Mesh Card and Add reboot Primary Node, Secondary (Garage) and Secondary node options with the data mesh included.  Maybe add a notification that states if you reset the Primary Both get rebooted...

And/Or

Help me fix or determine Why actions reboot doesn't work in the Node Cards.  I see the reboot under the second node but its not showing for the primary node.  I don't get why it doesn't show up under the Primary node, with the option to reboot there.

Thanks for all you do, love these cards.  Great for helping me troubleshot the network and find IP addresses for devices when needed.  Maybe one day, you could add a service to add devices, or rename them!

**Comment by uvjim** [comment]
> Help me fix or determine Why actions reboot doesn't work in the Node Cards. I see the reboot under the second node but its not showing for the primary node. I don't get why it doesn't show up under the Primary node, with the option to reboot there.

It isn't shown on the Primary node because as you've pointed out it will cause the whole mesh to reboot so I made the decision that it was a bit dangerous.  As you've spotted the Primary node can be rebooted easily enough using a service call so and the additional parameter, which makes doubly sure that you intended to do the reboot and didn't accidentally and blindly click a couple of buttons.

You are correct that it is broken though.  It's missing the reference to the mesh device.  I know exactly when this problem occurred as well, I just never got round to adding the functionality in after making the changes to the integration to allow multiple instances of it.  I'll have a look and see if I can get the information from the code used to build the buttons and let you know what I come up with.

> Thanks for all you do, love these cards. Great for helping me troubleshot the network and find IP addresses for devices when needed. Maybe one day, you could add a service to add devices, or rename them!

Adding devices seems a little redundant as they will appear once they have been connected to the Mesh.  Renaming them is a possiblity that I'll add to the list of things to look at.

**Comment by uvjim** [comment]
Right, could you test this please before I update the README with it.

```yaml
type: custom:auto-entities
card:
  type: vertical-stack
card_param: cards
sort:
  method: friendly_name
filter:
  exclude:
    - entity_id: /mesh/
  include:
    - entity_id: /binary_sensor\..*_status/
      or:
        - attributes:
            guest_network: true
        - attributes:
            guest_network: false
      options:
        type: custom:config-template-card
        variables:
          BUTTONS: |
            () => {
              let ret = []
              let entity_prefix = "button." + "this.entity_id".split(".")[1].split("_").slice(0, -1).join("_")
              for (let entity_id in states) {
                if (entity_id.startsWith(entity_prefix) && states[entity_id] != undefined) {
                  let entity_action = states[entity_id].attributes.friendly_name.replace(vars['ROOM_NAME'], '').replace(/velop|:/gi, '').trim()
                  let config_entry = this.hass.entities[entity_id].config_entry_id
                  let mesh_object = Object.entries(this.hass.devices).filter(([device_id, device_details]) => device_details.config_entries.indexOf(config_entry) != -1 && device_details.model.startsWith("pyvelop"))
                  if (mesh_object) {
                    let entity_name = vars['ROOM_NAME']
                    ret.push({
                      'entity': entity_id,
                      'name': entity_action,
                      'tap_action': {
                          'action': 'call-service',
                          'service': 'linksys_velop.' + entity_action.toLowerCase() + '_node',
                          'service_data': {
                            'mesh': mesh_object[0][0],
                            'node_name': entity_name,
                          },
                          'confirmation': {
                            'text': 'Are you sure you want to reboot the ' + entity_name + ' node?'
                        }
                      }
                    })
                  }
                }
              }
              return ret
            }
          ROOM_NAME: >
            states["this.entity_id"].attributes.friendly_name.replace(/Status|Velop|:/gi,
            "").trim()
          ID_BACKHAUL: >
            "sensor." + "this.entity_id".split(".")[1].split("_").slice(0,
            -1).join("_") + "_backhaul"
          ID_CONNECTED_DEVICES: >
            "sensor." + "this.entity_id".split(".")[1].split("_").slice(0,
            -1).join("_") + "_connected_devices"
          ID_ENTITY_PICTURE: >
            "sensor." + "this.entity_id".split(".")[1].split("_").slice(0,
            -1).join("_") + "_image"
          ID_LAST_UPDATE_CHECK: >
            "sensor." + "this.entity_id".split(".")[1].split("_").slice(0,
            -1).join("_") + "_last_update_check"
          ID_MODEL: >
            "sensor." +
            "this.entity_id".split(".")[1].split("_").slice(0,-1).join("_") +
            "_model"
          ID_PARENT: >
            "sensor." +
            "this.entity_id".split(".")[1].split("_").slice(0,-1).join("_") +
            "_parent"
          ID_SERIAL: >
            "sensor." +
            "this.entity_id".split(".")[1].split("_").slice(0,-1).join("_") +
            "_serial"
          ID_UPDATE_AVAILABLE: >
            "update." +
            "this.entity_id".split(".")[1].split("_").slice(0,-1).join("_") +
            "_update"
          CONNECTED_DEVICES_TEXT: |
            (entity_id) => {
              let ret = `
            | # | Name | IP | Type |
            |:---:|:---|---:|:---:|
            `
              if (states[entity_id] != undefined && states[entity_id].attributes.devices) {
                states[entity_id].attributes.devices.forEach((device, idx) => {
                  let connection_icon
                  switch (device.type.toLowerCase()) {
                    case "wireless":
                      connection_icon = "wifi"
                      break
                    case "wired":
                      connection_icon = "ethernet"
                      break
                    case "unknown":
                      connection_icon = "help"
                      break
                  }
                  ret += "| " + (idx + 1) + " | " + device.name + ((device.guest_network) ? "&nbsp;<ha-icon icon='hass:account-multiple'></ha-icon>" : "") + " | " + device.ip + " | <ha-icon icon='hass:" + connection_icon + "'></ha-icon> |\n"
                })
              }
              return ret
            }
          getEntityPicture: |
            () => {
              if (states[vars['ID_ENTITY_PICTURE']]) {
                return states[vars['ID_ENTITY_PICTURE']].state
              } else {
                if (states[vars['ID_MODEL']]) {
                    return '/local/velop_nodes/' + states[vars['ID_MODEL']].state + '.png'
                }
              }
            }
        entities:
          - this.entity_id
          - ${ID_BACKHAUL}
          - ${ID_CONNECTED_DEVICES}
          - ${ID_LAST_UPDATE_CHECK}
          - ${ID_MODEL}
          - ${ID_PARENT}
          - ${ID_SERIAL}
          - ${ID_UPDATE_AVAILABLE}
        card:
          type: entities
          card_mod:
            style:
              .: |
                #states { padding-top: 0px; }
              fold-entity-row:
                $:
                  template-entity-row:
                    $: |
                      state-badge { display: none; }
                      state-badge + div { margin-left: 8px !important; }
                      .info.pointer { font-weight: 500; }
                      .state { margin-right: 10px; }
          entities:
            - type: custom:button-card
              entity: this.entity_id
              size: 100%
              show_entity_picture: true
              show_last_changed: true
              show_state: true
              tap_action:
                action: none
              entity_picture: ${ getEntityPicture() }
              name: ${ROOM_NAME}
              state_display: |
                [[[
                  return `<ha-icon
                    icon="hass:checkbox-blank-circle"
                    style="width: 24px; height: 24px;">
                    </ha-icon>`
                ]]]
              custom_fields:
                attr_label_model: Model
                attr_model: '${((states[ID_MODEL]) ? states[ID_MODEL].state : undefined)}'
                attr_label_serial: Serial
                attr_serial: '${((states[ID_SERIAL]) ? states[ID_SERIAL].state : undefined)}'
                attr_parent: >-
                  ${(states[ID_PARENT] != undefined && states[ID_PARENT].state
                  && states[ID_PARENT].state != 'unknown') ? 'Connected to ' +
                  states[ID_PARENT].state : 'N/A'}
                attr_label_ip: IP Address
                attr_ip: '[[[ return entity.attributes.ip || ''N/A'' ]]]'
                attr_update: |
                  [[[
                    let ret
                    let entity_update = 'update.' + entity.entity_id.split('.')[1].split('_').slice(0, -1).join('_') + '_update'
                    if (states[entity_update] != undefined) {
                        let update_available = states[entity_update].state
                        if (update_available == 'on') {
                          ret = `<ha-icon
                              icon="hass:package-up"
                              style="width: 24px; height: 24px;"
                            >
                            </ha-icon>`
                        }
                    }
                    return ret
                  ]]]
              extra_styles: >
                div[id^="attr_"] { justify-self: end; } div[id^="attr_label_"] {
                justify-self: start; margin-left: 20px; } #label, #attr_parent {
                padding-top: 25px; font-size: smaller; }
              styles:
                card:
                  - border: 0
                  - box-shadow: none
                  - padding: 16px 8px
                grid:
                  - grid-template-areas: >-
                      "n n attr_update s" "i attr_label_model attr_label_model
                      attr_model" "i attr_label_serial attr_label_serial
                      attr_serial" "i attr_label_ip attr_label_ip attr_ip" "l l
                      l attr_parent"
                  - grid-template-columns: 15% 1fr 30px 30px
                name:
                  - font-size: larger
                  - justify-self: start
                  - padding-bottom: 20px
                label:
                  - justify-self: start
                custom_fields:
                  attr_label_last_update_check:
                    - margin-left: 0px
                  attr_last_update_check:
                    - justify-self: end
                  attr_parent:
                    - justify-self: end
                  attr_update:
                    - color: darkred
                    - justify-self: end
                    - padding-bottom: 20px
                state:
                  - justify-self: end
                  - padding-bottom: 20px
                  - color: |-
                      [[[
                        return (entity.state == 'on' ? 'darkcyan' : 'darkred')
                      ]]]
            - type: custom:auto-entities
              show_empty: false
              card:
                type: custom:fold-entity-row
                head:
                  type: section
                  label: Additional Information
                padding: 0
              filter:
                include:
                  - entity_id: ${ID_LAST_UPDATE_CHECK}
                    options:
                      name: Last update check
                  - entity_id: ${ID_BACKHAUL}
                    options:
                      type: custom:template-entity-row
                      name: Backhaul
                      secondary: >-
                        {% set backhaul_speed = state_attr(config.entity,
                        "speed_mbps") | round(2) %} {% if (backhaul_speed |
                        string).split('.')[1] == '0' %}
                          {% set backhaul_speed = backhaul_speed | int %}
                        {% endif %} {{ state_attr(config.entity, "connection")
                        }} ({{ backhaul_speed }} Mbps)
                      state: |-
                        {% if is_state(config.entity, 'unknown') %}
                          N/A
                        {% else %}
                          {{ state_attr(config.entity, 'signal_strength') }} ({{ states(config.entity) }} {{ state_attr(config.entity, 'unit_of_measurement') }})
                        {% endif %}
            - type: custom:auto-entities
              show_empty: false
              filter:
                include:
                  - domain: button
                    entity_id: >-
                      ${"/" +
                      "this.entity_id".split(".")[1].split("_").slice(0,-1).join("_")
                      + "/"}
              card:
                type: custom:fold-entity-row
                padding: 0
                head:
                  type: section
                  label: Actions
                entities:
                  - type: buttons
                    entities: ${BUTTONS()}
            - type: section
            - type: custom:fold-entity-row
              padding: 0
              head:
                type: custom:template-entity-row
                tap_action:
                  action: fire-dom-event
                  fold_row: true
                entity: ${ID_CONNECTED_DEVICES}
                name: Connected Devices
              entities:
                - type: custom:hui-element
                  card_type: markdown
                  content: ${CONNECTED_DEVICES_TEXT(ID_CONNECTED_DEVICES)}
                  card_mod:
                    style:
                      .: >
                        ha-card { border-radius: 0px; border: 0; box-shadow:
                        none; }

                        ha-markdown { padding: 16px 0px 0px !important; }
                      ha-markdown$: >
                        table { width: 100%; border-collapse: collapse; }

                        tbody tr:nth-child(2n+1) { background-color:
                        var(--table-row-background-color); }

                        thead tr th, tbody tr td { padding: 4px 10px; }
```
