### ISSUE TITLE
Scheduler card time selector stays black

### ISSUE THREAD

**Issue by jzielke84** [uvjim/linksys_velop#325]
I'm using the Google Dark theme for HA in conjunction with the scheduler card. However, the time selector is always black so I tried to change it with the following code:
```yaml
card_mod:
  style: |
    .mdc-text-field .mdc-text-field__input {
      color: white !important;
    }
```

However, no change is applied whatsoever. The cardmod plugin is working fine on normal ha-cards so I guess it's fully functional. Any suggestions?
![Bildschirmfoto 2022-11-22 um 11 06 43](https://user-images.githubusercontent.com/13448042/203286687-f64c821e-c13b-448b-84e0-933c82fc31a6.png)
