### ISSUE TITLE
New device found event doesn't trigger automation

### ISSUE THREAD

**Issue by bobbeims** [uvjim/linksys_velop#556]
I've set up an automation to let me know when a new device joins my mesh network, but the trigger doesn't seem to be working.

Here's the code I'm using for the automation:
```
alias: WiFi new device connected
description: >-
  When a new device connects to WiFi send a notification with a dump
  of the event data`
triggers:
  - trigger: state
    entity_id:
      - event.mesh_events
    attribute: event_type
    to: new_device_found
conditions: []
actions:
  - action: notify.mobile_app_iphone
    data:
      title: Linksys Velop
      message: >-
      New WiFi entity {% if trigger is defined and trigger is
      mapping and 'event' in trigger %} {{ trigger.event.data | tojson }} {%
      else %} No event data available {% endif %}
mode: queued
max: 10
```

I connected a new device to the WiFi and watched for a notification, but never got one. When I checked the traces for the automation I learned that it never fired.

But in the log for the event.mesh_events entity I see that a "New device found" event did occur:

<img width="592" alt="Image" src="https://github.com/user-attachments/assets/5584226c-ead5-4da8-a12e-1c0561045b1c" />

Is there something else I need to use as a trigger?

**Comment by uvjim** [comment]
Not as far as I know. If it isn't working for you, but the state is changing then it's probably a question for Home Assistant. However, I do have a similar notification for when I'm testing. Below is what I use (I assume this works because I don't track events very often).

```yaml
alias: "Notify: Linksys Velop Events"
description: ""
triggers:
  - entity_id:
      - event.mesh_events
    not_from:
      - unknown
      - unavailable
    trigger: state
conditions: []
actions:
  - if:
      - alias: Valid event?
        condition: template
        value_template: >-
          {{ trigger and trigger.to_state and
          trigger.to_state.attributes.event_type in ['mesh_rebooted',
          'mesh_rebooting', 'new_device_found', 'new_node_found'] }}
    then:
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ trigger.to_state.attributes.event_type in
                  ['mesh_rebooting', 'mesh_rebooted'] }}
            sequence:
              - action: persistent_notification.create
                metadata: {}
                data:
                  title: >-
                    {{ trigger.to_state.attributes.event_type | replace('_', '
                    ') | title }}
                  message: >-
                    {{ trigger.to_state.state | as_timestamp |
                    timestamp_custom('%a, %d %b %Y at %H:%M:%S') }}
            alias: Reboot event
          - conditions:
              - condition: template
                value_template: >-
                  {{ trigger.to_state.attributes.event_type in
                  ['new_device_found', 'new_node_found'] }}
            sequence:
              - variables:
                  name_mappings:
                    description: Description
                    guest_network: Guest Device
                    ip: IP
                    ipv6: IPv6
                    mac: MAC
                    manufacturer: Manufacturer
                    model: Model
                    name: Name
                    operating_system: Operating System
                    parent_name: Parent
                    reservation: Reserved Address
                    rssi: RSSI
                    serial: "Serial #"
                    signal_strength: Signal Strength
                  to_reject:
                    - backhaul
                    - event_type
                    - event_types
                    - friendly_name
                    - primary
                    - status
                    - unique_id
              - action: persistent_notification.create
                metadata: {}
                data:
                  title: >-
                    {{ trigger.to_state.attributes.event_type | replace('_', '
                    ') | title }}
                  message: >-
                    {% set ns = namespace(display={}) %}

                    {% for attr, val in trigger.to_state.attributes.items() if
                    val is not none and attr not in to_reject -%}
                      {% if attr == 'connected_adapters' and (val | length > 0) %}
                        {% set adapter = val[0] %}
                        {% for adapter_attr, adapter_val in adapter.items() if adapter_val is not none and adapter_attr not in to_reject %}
                          {% set ns.display = dict(ns.display, **{name_mappings.get(adapter_attr) or adapter_attr: adapter_val}) %}
                        {% endfor %}
                      {% else %}
                        {% set ns.display = dict(ns.display, **{name_mappings.get(attr) or attr: val}) %}
                      {% endif %}
                    {% endfor %}

                    ## {{ ns.display.get("Name") }}

                    |   |   |   |

                    |---|---|---|

                    {% for label, value in ns.display.items() if label | lower
                    != "name" -%}

                    |{{ label }}:|&emsp;|{{value}}|

                    {% endfor -%}
            alias: New device/node event
mode: parallel
max: 10
```
